=encoding utf8

=head1 Парсер номеров телефонов VK

Скрипт на языке програмирования Perl для сбора номеров украинских операторов из социальной сети vk.com

=head2 Фишки

[*] Определение оператора связи (Utel, PeopleNET, Intertelecom, MTS, Life, KievStar)
[*] Не проверяет страницы пользователей номера которых уже были собраны
[*] Асинхронные запросы к сайту использую Coro вместо форков или потоков
[*] Для сокращения трафика используется предварительная проверка на наличие номера через API

=head2 Help

usage: start.pl [OPTIONS...]

  Options:
    --first,   -f   ID первого пользователя
    --last,    -l   ID последнего пользователя
    --db,      -d   Расположение базы данных SQLite
    --threads, -t   Количество потоков
    --help,    -h   Отобразить это сообщение
