=encoding utf8

=head1 VK phone nambers parser

Script based on Perl language which collect mobile numbers of ukranian operators from vk.com social network.

=head2 Features

	[*] Определение оператора связи (Utel, PeopleNET, Intertelecom, MTS, Life, KievStar)
	[*] Не проверяет страницы пользователей номера которых уже были собраны
	[*] Асинхронные запросы к сайту использую Coro вместо форков или потоков
	[*] Для сокращения трафика используется предварительная проверка на наличие номера через API

=head2 Help

usage: start.pl [OPTIONS...]

  Options:
    --first,   -f   First user ID
    --last,    -l   Last user ID
    --db,      -d   SQLite databse location
    --threads, -t   Threads count
    --help,    -h   Show this help message
